replicaCount: 2

image:
  repository: your-registry/go-ws-gateway-proxy
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  # ─── single source of truth for your public host ───
  # used in the IngressRoute Host(...) match and TLS hosts
  host: ws-public-host-name.example.com
  # ─── single source of truth for CORS/allowed origins ───
  # used in the CORS middleware
  allowedOrigins: "*.example.com"
  tls:
    secretName: tls-secret

# ------------------------------------------------------------------
# WebSocket routing table
# Each entry is matched by URL prefix inside the proxy; customise as
# needed or override per-environment.
# ------------------------------------------------------------------
gatewayRoutes:
  - prefix: /livekit
    upstream: ws://livekit-signal.media.svc.cluster.local:7880/signal
    copySubProtocol: true
    preserveQuery: true

  - prefix: /mqtt
    upstream: ws://rabbitmq-mqtt.messaging.svc.cluster.local:15675/ws
    copySubProtocol: false
    preserveQuery: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: # Projected into ConfigMap
  WS_ALLOWED_ORIGINS: "*.example.com"
  JWT_COOKIE_NAME: "session"
  GRACEFUL_DRAIN_TIMEOUT_SECONDS: "30"
  WS_IDLE_TIMEOUT_SECONDS: "60"
  WS_WRITE_TIMEOUT_SECONDS: "10"
  WS_CONTROL_TIMEOUT_SECONDS: "1"
  CB_FAILURE_THRESHOLD: "5"
  CB_OPEN_TIMEOUT_SECONDS: "60"
  CB_HEALTHCHECK_INTERVAL_SECONDS: "30"
  WS_DIAL_RETRY_MAX: "3"
  WS_DIAL_RETRY_INTERVAL_SECONDS: "2"
  RATE_LIMIT_PER_SECOND: "10"
  RATE_LIMIT_BURST: "30"
  JWKS_URL: "https://keycloak.example.com/realms/myrealm/protocol/openid-connect/certs"
  JWKS_TTL_MINUTES: "10"
  JWT_CACHE_STORE: "redis"
  JWT_CACHE_PREFIX: "jwt_cached_token_"

secrets: # Projected into Kubernetes Secret
  JWT_EXPECTED_ISSUER: "https://keycloak.example.com/realms/myrealm"
  JWT_EXPECTED_AUDIENCE: "rabbitmq"
  JWT_VALID_ALGORITHMS: "RS256"
  REDIS_URL: ""
  POSTGRES_DSN: ""
  UPSTREAM_WS_URL: "ws://rabbitmq:15675/ws"
