apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-ws-gateway-proxy.fullname" . }}
  labels:
    {{- include "go-ws-gateway-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "go-ws-gateway-proxy.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "go-ws-gateway-proxy.name" . }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8080
              name: http
          # env:
          #   {{- range $k, $v := .Values.env }}
          #   - name: {{ $k }}
          #     value: "{{ $v }}"
          #   {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "go-ws-gateway-proxy.fullname" . }}-config
            - secretRef:
                name: {{ include "go-ws-gateway-proxy.fullname" . }}-secrets
          volumeMounts:
            - name: route-config
              mountPath: /etc/ws-gw
              readOnly: true
          args:
            - "--route-file=/etc/ws-gw/routes.yaml"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    echo "Draining connections for ${GRACEFUL_DRAIN_TIMEOUT_SECONDS}s"
                    sleep ${GRACEFUL_DRAIN_TIMEOUT_SECONDS}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: route-config
          configMap:
            name: {{ include "go-ws-gateway-proxy.fullname" . }}-routes
